
CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR(100) UNIQUE NOT NULL,
  "name" VARCHAR(90) NOT NULL,
  "lastname" VARCHAR(90) NOT NULL,
  "phone" VARCHAR(90) UNIQUE NOT NULL,
  "image" VARCHAR(255) NOT NULL,
  "password" VARCHAR(90) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "image" varchar(90),
  "route" varchar(180) NOT NULL,
  "created_at" timestamp(0) NOT NULL
);

CREATE TABLE "user_has_roles" (
  "id_user" bigint NOT NULL,
  "id_rol" bigint NOT NULL,
  "created_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id_user", "id_rol")
);
CREATE TABLE "sessions"(
  "id" uuid PRIMARY KEY,
  "email" VARCHAR NOT NULL,
  "refresh_token" VARCHAR NOT NULL,
  "user_agent" VARCHAR NOT NULL,
  "client_ip" VARCHAR NOT NULL,
  "is_blocked" boolean NOT NULL DEFAULT false,
  "expires_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

ALTER TABLE "sessions" ADD FOREIGN KEY ("email") REFERENCES "users" ("email");


ALTER TABLE "user_has_roles" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "user_has_roles" ADD FOREIGN KEY ("id_rol") REFERENCES "roles" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
