// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Role struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Image     sql.NullString `json:"image"`
	Route     string         `json:"route"`
	CreatedAt time.Time      `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Lastname  string    `json:"lastname"`
	Phone     string    `json:"phone"`
	Image     string    `json:"image"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}

type UserHasRole struct {
	IDUser    int64     `json:"id_user"`
	IDRol     int64     `json:"id_rol"`
	CreatedAt time.Time `json:"created_at"`
}
