CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR(100) UNIQUE NOT NULL,
  "name" VARCHAR(90) NOT NULL,
  "lastname" VARCHAR(90) NOT NULL,
  "phone" VARCHAR(90) UNIQUE NOT NULL,
  "image" VARCHAR(255) NOT NULL,
  "password" VARCHAR(90) NOT NULL,
  "created_at" TIMESTAMP(0) NOT NULL
);

CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "image" varchar(90),
  "route" varchar(180) NOT NULL,
  "created_at" timestamp(0) NOT NULL
);

CREATE TABLE "user_has_roles" (
  "id_user" bigint NOT NULL,
  "id_rol" bigint NOT NULL,
  "created_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id_user", "id_rol")
);

ALTER TABLE "user_has_roles" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "user_has_roles" ADD FOREIGN KEY ("id_rol") REFERENCES "roles" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
